# shell or sample makefile for fpc
# see https://bytes.usc.edu/cs104/wiki/makefile/ for a quick reference

solution: dsmetrics.pas
	fpc -glw3 -Ciort -ap -Sgix -vewnlb dsmetrics

clean:
	rm -f dsmetrics dsmetrics.o
